export const FAKE_BUILD_LOG = [
  "Processing fx3u_24_raw (platform: ststm32)",
  "--------------------------------------------------------------------------------",
  "Verbose mode can be enabled via `-v, --verbose` option",
  "[openplc] pre-build: IEC 61131-3 -> C (MatIEC)",
  "[openplc] source: plc/plc_prog.st (changed since last build)",
  "[openplc] cleaning stale src/plc/* (8 files)",
  "Compiling plc_prog.st ...",
  "  st_optimizer plc/plc_prog.st -> .pio/openplc/plc_prog.st",
  "  iec2c -f -l -p -r -R -a -I lib/matiec -T src/plc .pio/openplc/plc_prog.st",
  "  [stage 1-2] lexical + syntax analysis .......... OK",
  "  [stage 3]   semantic analysis + type checks .... OK",
  "  [stage 4]   C code generation .................. OK",
  "  POUs:",
  "    PROGRAM         MAIN",
  "    FUNCTION_BLOCK  MOTOR_STARTER",
  "    FUNCTION_BLOCK  CONVEYOR_CTRL",
  "    FUNCTION_BLOCK  ALARM_LATCH",
  "    FUNCTION        SCALE_AIN",
  "  std FBs: TON x4, TOF x1, R_TRIG x3, F_TRIG x1, CTU x2",
  "  vars: 41 local, 34 located, 4 retain",
  "  CONFIGURATION Config0 / RESOURCE Res0",
  "  TASK task0 (INTERVAL := T#20ms, PRIORITY := 0)",
  "  PROGRAM instance0 WITH task0 : MAIN",
  "  generated src/plc/POUS.c",
  "  generated src/plc/POUS.h",
  "  generated src/plc/Config0.c",
  "  generated src/plc/Config0.h",
  "  generated src/plc/Res0.c",
  "  generated src/plc/LOCATED_VARIABLES.h",
  "  generated src/plc/VARIABLES.csv",
  "  common_ticktime__ = 20000000 ns (20 ms scan)",
  "[openplc] glue generator: LOCATED_VARIABLES.h -> glueVars.c",
  "  %IX0.0   bool_input[0][0]    X0",
  "  %IX0.1   bool_input[0][1]    X1",
  "  %IX0.2   bool_input[0][2]    X2",
  "  %IX0.3   bool_input[0][3]    X3",
  "  %IX0.4   bool_input[0][4]    X4",
  "  %IX0.5   bool_input[0][5]    X5",
  "  %IX0.6   bool_input[0][6]    X6",
  "  %IX0.7   bool_input[0][7]    X7",
  "  %IX1.0   bool_input[1][0]    X10",
  "  %IX1.1   bool_input[1][1]    X11",
  "  %IX1.2   bool_input[1][2]    X12",
  "  %IX1.3   bool_input[1][3]    X13",
  "  %IX1.4   bool_input[1][4]    X14",
  "  %IX1.5   bool_input[1][5]    X15",
  "  %QX0.0   bool_output[0][0]   Y0",
  "  %QX0.1   bool_output[0][1]   Y1",
  "  %QX0.2   bool_output[0][2]   Y2",
  "  %QX0.3   bool_output[0][3]   Y3",
  "  %QX0.4   bool_output[0][4]   Y4",
  "  %QX0.5   bool_output[0][5]   Y5",
  "  %QX0.6   bool_output[0][6]   Y6",
  "  %QX0.7   bool_output[0][7]   Y7",
  "  %QX1.0   bool_output[1][0]   Y10",
  "  %QX1.1   bool_output[1][1]   Y11",
  "  %IW0     int_input[0]        AD0",
  "  %IW1     int_input[1]        AD1",
  "  %MW0     int_memory[0]       HR 1024",
  "  %MW1     int_memory[1]       HR 1025",
  "  %MW2     int_memory[2]       HR 1026",
  "  %MW3     int_memory[3]       HR 1027",
  "  %MW4     int_memory[4]       HR 1028",
  "  %MW5     int_memory[5]       HR 1029",
  "  %MW6     int_memory[6]       HR 1030",
  "  %MW7     int_memory[7]       HR 1031",
  "  located: 14 DI, 10 DO, 2 AI, 8 MW",
  "  generated src/plc/glueVars.c",
  "[openplc] retain: 4 vars -> EEPROM emulation (last 2 KB flash page)",
  "[openplc] modbus map (slave 1, RS232 / USART1 @ 115200 8N1)",
  "  coils              %QX0.0-%QX1.1   0-9",
  "  discrete inputs    %IX0.0-%IX1.5   0-13",
  "  input registers    %IW0-%IW1       0-1",
  "  holding registers  %MW0-%MW7       1024-1031",
  "[openplc] pre-build finished in 0.92 s",
  "CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/genericSTM32F103VC.html",
  "PLATFORM: ST STM32 (19.1.0) > STM32F103VC (48k RAM. 256k Flash)",
  "HARDWARE: STM32F103VCT6 72MHz, 48KB RAM, 256KB Flash",
  "DEBUG: Current (stlink) External (blackmagic, cmsis-dap, jlink, stlink)",
  "PACKAGES:",
  " - framework-arduinoststm32 @ 4.20900.241028 (2.9.0)",
  " - framework-cmsis @ 2.50900.0 (5.9.0)",
  " - tool-dfuutil @ 1.11.0",
  " - tool-openocd @ 3.1200.0 (12.0)",
  " - tool-stm32duino @ 1.0.2",
  " - toolchain-gccarmnoneeabi @ 1.120301.0 (12.3.1)",
  "LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf",
  "LDF Modes: Finder ~ chain, Compatibility ~ soft",
  "Found 19 compatible libraries",
  "Scanning dependencies...",
  "Dependency Graph",
  "|-- ModbusRTU_Slave @ 1.2.0",
  "|-- EEPROM @ 2.0.1",
  "|-- IWatchdog @ 1.0.0",
  "Building in release mode",
  "Compiling src/comm/modbus_map.cpp.o",
  "Compiling src/comm/serial_port.cpp.o",
  "Compiling src/hal/analog_in.cpp.o",
  "src/hal/analog_in.cpp: In function 'void analog_poll()':",
  "src/hal/analog_in.cpp:38:12: warning: unused variable 'raw_prev' [-Wunused-variable]",
  "   38 |   uint16_t raw_prev = 0;",
  "      |            ^~~~~~~~",
  "Compiling src/hal/din_filter.cpp.o",
  "Compiling src/hal/fx3u_24_raw.cpp.o",
  "Compiling src/hal/hs_counter.cpp.o",
  "Compiling src/hal/pulse_out.cpp.o",
  "Compiling src/hal/run_stop.cpp.o",
  "Compiling src/hal/status_leds.cpp.o",
  "Compiling src/main.cpp.o",
  "Compiling src/plc/Config0.c.o",
  "Compiling src/plc/Res0.c.o",
  "Compiling src/plc/glueVars.c.o",
  "Compiling src/runtime/diagnostics.cpp.o",
  "Compiling src/runtime/plc_debug.cpp.o",
  "Compiling src/runtime/retain.cpp.o",
  "Compiling src/runtime/rtc_clock.cpp.o",
  "Compiling src/runtime/scan_cycle.cpp.o",
  "Compiling src/runtime/watchdog.cpp.o",
  "Compiling lib3a1/ModbusRTU_Slave/ModbusRTUSlave.cpp.o",
  "Compiling lib3a1/ModbusRTU_Slave/crc16.cpp.o",
  "Compiling lib3a1/ModbusRTU_Slave/frame_timer.cpp.o",
  "Compiling lib3a1/ModbusRTU_Slave/register_table.cpp.o",
  "Archiving lib3a1/libModbusRTU_Slave.a",
  "Indexing lib3a1/libModbusRTU_Slave.a",
  "Compiling lib8c4/EEPROM/utility/stm32_eeprom.c.o",
  "Archiving lib8c4/libEEPROM.a",
  "Indexing lib8c4/libEEPROM.a",
  "Compiling libf52/IWatchdog/IWatchdog.cpp.o",
  "Archiving libf52/libIWatchdog.a",
  "Indexing libf52/libIWatchdog.a",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_adc.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_adc_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_can.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_cec.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_comp.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_comp_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_cordic.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_cortex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_crc.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_crc_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_cryp.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_cryp_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_dac.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_dac_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_dcache.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_dcmi.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_dcmi_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_dfsdm.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_dfsdm_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_dma.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_dma2d.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_dma_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_dsi.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_dts.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_eth.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_eth_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_exti.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_fdcan.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_firewall.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_flash.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_flash_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_flash_ramfunc.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_fmac.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_fmpi2c.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_fmpi2c_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_fmpsmbus.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_fmpsmbus_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_gfxmmu.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_gfxtim.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_gpio.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_gpio_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_gpu2d.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_gtzc.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_hash.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_hash_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_hcd.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_hrtim.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_hsem.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_i2c.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_i2c_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_i2s.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_i2s_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_i3c.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_icache.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_ipcc.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_irda.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_iwdg.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_jpeg.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_lcd.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_lptim.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_ltdc.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_ltdc_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_mdf.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_mdios.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_mdma.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_mmc.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_mmc_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_nand.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_nor.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_opamp.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_opamp_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_ospi.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_otfdec.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_pccard.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_pcd.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_pcd_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_pka.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_pssi.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_pwr.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_pwr_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_qspi.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_ramcfg.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_ramecc.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_rcc.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_rcc_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_rng.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_rng_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_rtc.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_rtc_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_sai.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_sai_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_sd.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_sd_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_sdadc.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_sdram.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_smartcard.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_smartcard_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_smbus.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_smbus_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_spdifrx.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_spi.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_spi_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_sram.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_subghz.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_swpmi.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_tim.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_tim_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_tsc.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_uart.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_uart_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_usart.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_usart_ex.c.o",
  "Compiling SrcWrapper/src/HAL/stm32yyxx_hal_wwdg.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_adc.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_bdma.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_comp.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_cordic.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_crc.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_crs.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_dac.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_delayblock.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_dma.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_dma2d.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_exti.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_fmac.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_fmc.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_fmpi2c.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_fsmc.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_gpio.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_hrtim.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_i2c.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_i3c.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_icache.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_ipcc.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_lpgpio.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_lptim.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_lpuart.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_mdma.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_opamp.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_pka.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_pwr.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_rcc.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_rng.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_rtc.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_sdmmc.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_spi.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_swpmi.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_tim.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_ucpd.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_usart.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_usb.c.o",
  "Compiling SrcWrapper/src/LL/stm32yyxx_ll_utils.c.o",
  "Compiling SrcWrapper/src/new.cpp.o",
  "Compiling SrcWrapper/src/stm32/PortNames.c.o",
  "Compiling SrcWrapper/src/stm32/analog.cpp.o",
  "Compiling SrcWrapper/src/stm32/bootloader.c.o",
  "Compiling SrcWrapper/src/stm32/clock.c.o",
  "Compiling SrcWrapper/src/stm32/core_callback.c.o",
  "Compiling SrcWrapper/src/stm32/dwt.c.o",
  "Compiling SrcWrapper/src/stm32/hw_config.c.o",
  "Compiling SrcWrapper/src/stm32/interrupt.cpp.o",
  "Compiling SrcWrapper/src/stm32/lock_resource.c.o",
  "Compiling SrcWrapper/src/stm32/otp.c.o",
  "Compiling SrcWrapper/src/stm32/pinmap.c.o",
  "Compiling SrcWrapper/src/stm32/stm32_def.c.o",
  "Compiling SrcWrapper/src/stm32/system_stm32yyxx.c.o",
  "Compiling SrcWrapper/src/stm32/timer.c.o",
  "Compiling SrcWrapper/src/stm32/uart.c.o",
  "Compiling SrcWrapper/src/syscalls.c.o",
  "Compiling FrameworkArduinoVariant/PeripheralPins.c.o",
  "Compiling FrameworkArduinoVariant/generic_clock.c.o",
  "Compiling FrameworkArduinoVariant/variant_generic.cpp.o",
  "Archiving libFrameworkArduinoVariant.a",
  "Indexing libFrameworkArduinoVariant.a",
  "Compiling FrameworkArduino/HardwareSerial.cpp.o",
  "Compiling FrameworkArduino/HardwareTimer.cpp.o",
  "Compiling FrameworkArduino/IPAddress.cpp.o",
  "Compiling FrameworkArduino/Print.cpp.o",
  "Compiling FrameworkArduino/Stream.cpp.o",
  "Compiling FrameworkArduino/Tone.cpp.o",
  "Compiling FrameworkArduino/USBSerial.cpp.o",
  "Compiling FrameworkArduino/VirtIOSerial.cpp.o",
  "Compiling FrameworkArduino/WInterrupts.cpp.o",
  "Compiling FrameworkArduino/WMath.cpp.o",
  "Compiling FrameworkArduino/WSerial.cpp.o",
  "Compiling FrameworkArduino/WString.cpp.o",
  "Compiling FrameworkArduino/abi.cpp.o",
  "Compiling FrameworkArduino/avr/dtostrf.c.o",
  "Compiling FrameworkArduino/board.c.o",
  "Compiling FrameworkArduino/core_debug.c.o",
  "Compiling FrameworkArduino/hooks.c.o",
  "Compiling FrameworkArduino/itoa.c.o",
  "Compiling FrameworkArduino/main.cpp.o",
  "Compiling FrameworkArduino/pins_arduino.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/libmetal/device.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/libmetal/generic/condition.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/libmetal/generic/cortexm/sys.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/libmetal/generic/generic_device.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/libmetal/generic/generic_init.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/libmetal/generic/generic_io.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/libmetal/generic/generic_shmem.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/libmetal/generic/time.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/libmetal/init.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/libmetal/io.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/libmetal/log.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/libmetal/shmem.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/mbox_ipcc.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/open-amp/remoteproc/remoteproc_virtio.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/open-amp/rpmsg/rpmsg.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/open-amp/rpmsg/rpmsg_virtio.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/openamp.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/rsc_table.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/virt_uart.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/virtio/virtio.c.o",
  "Compiling FrameworkArduino/stm32/OpenAMP/virtio/virtqueue.c.o",
  "Compiling FrameworkArduino/stm32/startup_stm32yyxx.S.o",
  "Compiling FrameworkArduino/stm32/usb/cdc/cdc_queue.c.o",
  "Compiling FrameworkArduino/stm32/usb/cdc/usbd_cdc.c.o",
  "Compiling FrameworkArduino/stm32/usb/cdc/usbd_cdc_if.c.o",
  "Compiling FrameworkArduino/stm32/usb/hid/usbd_hid_composite.c.o",
  "Compiling FrameworkArduino/stm32/usb/hid/usbd_hid_composite_if.c.o",
  "Compiling FrameworkArduino/stm32/usb/usb_device_core.c.o",
  "Compiling FrameworkArduino/stm32/usb/usb_device_ctlreq.c.o",
  "Compiling FrameworkArduino/stm32/usb/usb_device_ioreq.c.o",
  "Compiling FrameworkArduino/stm32/usb/usbd_conf.c.o",
  "Compiling FrameworkArduino/stm32/usb/usbd_desc.c.o",
  "Compiling FrameworkArduino/stm32/usb/usbd_ep_conf.c.o",
  "Compiling FrameworkArduino/stm32/usb/usbd_if.c.o",
  "Compiling FrameworkArduino/wiring_analog.c.o",
  "Compiling FrameworkArduino/wiring_digital.c.o",
  "Compiling FrameworkArduino/wiring_pulse.cpp.o",
  "Compiling FrameworkArduino/wiring_shift.c.o",
  "Compiling FrameworkArduino/wiring_time.c.o",
  "Archiving libFrameworkArduino.a",
  "Indexing libFrameworkArduino.a",
  "Linking firmware.elf",
  "Checking size firmware.elf",
  'Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"',
  "RAM:   [==        ]  18.4% (used 9048 bytes from 49152 bytes)",
  "Flash: [===       ]  33.1% (used 86804 bytes from 262144 bytes)",
  "Building firmware.bin",
  "[post] arm-none-eabi-size -A firmware.elf",
  "firmware.elf  :",
  "section              size        addr",
  ".isr_vector           304   134217728",
  ".text               79428   134218032",
  ".rodata              5580   134297460",
  ".ARM.extab              0   134303040",
  ".ARM                    8   134303040",
  ".preinit_array          0   134303048",
  ".init_array            12   134303048",
  ".fini_array             4   134303060",
  ".data                1468   536870912",
  ".bss                 6044   536872380",
  "._user_heap_stack    1536   536878424",
  ".ARM.attributes        41           0",
  ".comment               67           0",
  "Total               94492",
  "[post] top symbols by size:",
  "  2968  T  MAIN_body__",
  "  1812  T  uart_init",
  "  1296  T  ModbusRTUSlave::poll()",
  "  1104  T  HAL_RCC_OscConfig",
  "   968  T  __aeabi_dadd",
  "   712  T  __udivmoddi4",
  "[post] firmware.bin  86,804 bytes  crc32 0x5c1e9a07",
  "[post] objcopy -O ihex firmware.elf firmware.hex",
  "[post] copied -> dist/fx3u_24_raw.bin, dist/fx3u_24_raw.hex",
  "========================= [SUCCESS] Took 47.31 seconds =========================",
];
